spring.application.name=usuario

spring.datasource.url=jdbc:postgresql://localhost:5432/db_usuario_habitos
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=8z8vB6B3n2z5C8D1G4J7M0Q3S6V9Y2B5E8H1K4M7P0S3V6Y9